### ISSUE TITLE
ES Modules vs namespaces

### ISSUE THREAD

**Issue by paradis-A** [Franatrtur/ulurujs#2]
i know this library is written in typescript but could make it work in typescript :(
see images below
![uluru error](https://user-images.githubusercontent.com/42695235/148892792-4763c747-4e85-41a8-95f6-3fd68aae39ee.JPG)
![uluru message](https://user-images.githubusercontent.com/42695235/148892815-24102dc6-e055-45f3-900e-3721d33af7a4.JPG)

**Comment by paradis-A** [comment]
Sorry i was hyped when i found this hidden gem then i could think straight coz been looking for lightweight crypto solution without the use of  SubtleCrypto for days now. Then i finnaly found this hidden gem.

```typescript
import "uluru-crypto";
const {encrypt,decrypt} = Uluru
```

I already came up with solution, it works but some people like me may not be get used to code above. They may not figure out and pass on this gem.

**Comment by Franatrtur** [comment]
Glad to see that someone actually uses this 😄.
Actually the main reason I used typescript was for compilation of many files into one (so the same compiled file can also be used in browser) and self-documentation. If you are experienced with typescript, is there something you would change for better support, or a simple fix to the problem you described? Thanks!

Note: The latest version of uluru-crypto has a different pbkdf function!

**Comment by paradis-A** [comment]
Everything is good, i dont even know you can write bundle with namespaces  as i use rollup some ts plugins to build single file. I dont know much how namespaces works when import i.e. if every modules has been loaded when importing a namespace or it works just like any other modules that you can only choose what to import.

**Comment by Franatrtur** [comment]
Major update done! Now uluru should be stable, no more annoying changes in typings. If anyone ends up using it in any project, let me know! When I did some tests on files it came out 10x faster than crypto-js.

> Everything is good, i dont even know you can write bundle with namespaces as i use rollup some ts plugins to build single file.

That sounds promising already! Can you please share what plugins you use to compile many ts files into one js? I would consider making a branch for esm.

**Comment by paradis-A** [comment]
I'll give this update a try later on. I use [Rollup](https://rollupjs.org/guide/en/) for bundling my libraries, you can checkout my usual rollup config  [here](https://github.com/paradis-A/lendb-client/blob/038f92aa06acdc155b6f91cd6a1ab62a6ff7425b/rollup.config.js).

**Comment by Franatrtur** [comment]
Alright! Rollup works wonders, thank you for the suggestion @paradis-A. Feel free to check out the [esm branch](https://github.com/Franatrtur/ulurujs/tree/esm) and let me know what you think! Should I make this the main branch or just merge it with a pull request?
Only a few big commits, restructuring the whole library for esm, and development already feels much more convenient. Now I am looking to improve testing with something like jest. Also I will need to update the docs.

**Comment by Franatrtur** [comment]
With  the #3 pull request, the Ulurucrypto module is fully transfering to ESM modules, that closes this issue :D
